### ISSUE TITLE
Client Crash in v14

### ISSUE THREAD

**Issue by biomatter** [AKA-Syenite/WarpTheory#4]
I swear I don't have it out for you, Shukaro. I just... feel the need to do my due diligence in reporting these things.
Crash logs: http://pastebin.com/P5dfCCPc
Crash logs: http://pastebin.com/kHyifeTv
They look identical to me, something about WarpEars or sumtin'. They only drop my client, not the server, so that's nice. It's pretty harmless, only happens about once an hour, so I'm making do.

Edit: Ok, I've noticed it seems to crash any time I try to type something. As soon as I press enter, crash.

**Comment by AKA-Syenite** [comment]
Fixed by 83c47d3302cb5726e1f76b45bbe5348aee648b2b
