### ISSUE TITLE
Client Crash in v16

### ISSUE THREAD

**Issue by biomatter** [AKA-Syenite/WarpTheory#5]
I do this because I love you.
Crash log: http://pastebin.com/4QYTpN3d
Client side only. Server lived through it. I was playing alone and I didn't see this crash until a friend logged in, and now we are crashing semi-frequently. We usually crash at the same time, but once I lived through when my friend didn't. Not sure why yet. Will report back if I figure anything out.

**Comment by AKA-Syenite** [comment]
Fixed by 950f143f0b6ba78e3f175147aefdad115f4ef7be
