### ISSUE TITLE
Server Crash in v17

### ISSUE THREAD

**Issue by biomatter** [AKA-Syenite/WarpTheory#6]
I swear this is the last one I'll submit tonight. Sorry for keeping you so busy.
Crash log: http://pastebin.com/HidsiRLN
I got a message saying 'Your tongue goes numb...' and since there were no obvious changes, I decided to try messaging. Server crashed, client was booted out but seemed intact.

**Comment by AKA-Syenite** [comment]
Fixed by df6bf00570966097dd856da9de73d5b7c7352f5f
